/**
 * TryHarder Security Suite - Export Utilities
 * Author: a0x194 (https://github.com/a0x194)
 */

export const Export = {
  /**
   * Export results in various formats
   */
  exportResults(results, format) {
    const timestamp = new Date().toISOString().slice(0, 19).replace(/[:-]/g, '');
    const filename = `tryharder-results-${timestamp}`;

    switch (format) {
      case 'json':
        this.downloadJSON(results, filename);
        break;
      case 'csv':
        this.downloadCSV(results, filename);
        break;
      case 'markdown':
        this.downloadMarkdown(results, filename);
        break;
      case 'html':
        this.downloadHTML(results, filename);
        break;
      default:
        console.error('Unknown export format:', format);
    }
  },

  /**
   * Download as JSON
   */
  downloadJSON(results, filename) {
    const data = JSON.stringify(results, null, 2);
    this.download(data, `${filename}.json`, 'application/json');
  },

  /**
   * Download as CSV
   */
  downloadCSV(results, filename) {
    let csv = 'Tool,Type,Title,Value,Severity,Timestamp\n';

    for (const [tool, toolResults] of Object.entries(results)) {
      if (Array.isArray(toolResults)) {
        toolResults.forEach(result => {
          csv += `"${tool}","${result.type || ''}","${this.escapeCSV(result.title || '')}","${this.escapeCSV(result.value || '')}","${result.severity || ''}","${result.timestamp || ''}"\n`;
        });
      }
    }

    this.download(csv, `${filename}.csv`, 'text/csv');
  },

  /**
   * Download as Markdown
   */
  downloadMarkdown(results, filename) {
    let md = `# TryHarder Security Suite Report\n\n`;
    md += `**Generated:** ${new Date().toISOString()}\n\n`;
    md += `---\n\n`;

    for (const [tool, toolResults] of Object.entries(results)) {
      if (Array.isArray(toolResults) && toolResults.length > 0) {
        md += `## ${tool.toUpperCase()}\n\n`;
        md += `Found **${toolResults.length}** results\n\n`;

        toolResults.forEach((result, index) => {
          md += `### ${index + 1}. ${result.title || 'Finding'}\n\n`;
          if (result.type) md += `- **Type:** ${result.type}\n`;
          if (result.severity) md += `- **Severity:** ${result.severity}\n`;
          if (result.value) md += `- **Value:** \`${result.value}\`\n`;
          if (result.subtitle) md += `- **Details:** ${result.subtitle}\n`;
          md += `\n`;
        });

        md += `---\n\n`;
      }
    }

    md += `\n---\n\n*Report generated by [TryHarder Security Suite](https://www.tryharder.space) by [a0x194](https://github.com/a0x194)*\n`;

    this.download(md, `${filename}.md`, 'text/markdown');
  },

  /**
   * Download as HTML Report
   */
  downloadHTML(results, filename) {
    let totalFindings = 0;
    let high = 0, medium = 0, low = 0;

    for (const toolResults of Object.values(results)) {
      if (Array.isArray(toolResults)) {
        toolResults.forEach(result => {
          totalFindings++;
          if (result.severity === 'high' || result.severity === 'critical') high++;
          else if (result.severity === 'medium') medium++;
          else low++;
        });
      }
    }

    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TryHarder Security Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', -apple-system, sans-serif;
      background: #0a0f0a;
      color: #e0ffe0;
      line-height: 1.6;
      padding: 20px;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    header {
      text-align: center;
      padding: 40px 0;
      border-bottom: 1px solid #1a3a1a;
      margin-bottom: 30px;
    }
    h1 {
      font-size: 2.5rem;
      color: #00ff88;
      margin-bottom: 10px;
    }
    .subtitle { color: #88aa88; }
    .stats {
      display: flex;
      justify-content: center;
      gap: 40px;
      margin-top: 30px;
    }
    .stat {
      text-align: center;
      padding: 20px;
      background: #111a11;
      border-radius: 8px;
      min-width: 120px;
    }
    .stat-value {
      font-size: 2rem;
      font-weight: 700;
      color: #00ff88;
    }
    .stat-label {
      font-size: 0.875rem;
      color: #5a7a5a;
      text-transform: uppercase;
    }
    .stat.high .stat-value { color: #ff4757; }
    .stat.medium .stat-value { color: #ffa502; }
    .stat.low .stat-value { color: #3498db; }
    section {
      margin-bottom: 40px;
    }
    h2 {
      font-size: 1.5rem;
      color: #00ff88;
      padding: 15px 0;
      border-bottom: 1px solid #1a3a1a;
      margin-bottom: 20px;
    }
    .result {
      background: #111a11;
      border: 1px solid #1a3a1a;
      border-radius: 8px;
      padding: 15px;
      margin-bottom: 10px;
    }
    .result:hover { border-color: rgba(0, 255, 136, 0.3); }
    .result-title {
      font-weight: 600;
      margin-bottom: 5px;
    }
    .result-value {
      font-family: monospace;
      background: #000;
      padding: 8px 12px;
      border-radius: 4px;
      color: #00ff88;
      font-size: 0.875rem;
      word-break: break-all;
      margin-top: 10px;
    }
    .severity {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      margin-left: 10px;
    }
    .severity.critical, .severity.high { background: rgba(255, 71, 87, 0.2); color: #ff4757; }
    .severity.medium { background: rgba(255, 165, 2, 0.2); color: #ffa502; }
    .severity.low, .severity.info { background: rgba(0, 255, 136, 0.2); color: #00ff88; }
    footer {
      text-align: center;
      padding: 30px;
      border-top: 1px solid #1a3a1a;
      margin-top: 40px;
      color: #5a7a5a;
    }
    footer a { color: #00ff88; text-decoration: none; }
    footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>TryHarder Security Report</h1>
      <p class="subtitle">Generated: ${new Date().toLocaleString()}</p>
      <div class="stats">
        <div class="stat">
          <div class="stat-value">${totalFindings}</div>
          <div class="stat-label">Total Findings</div>
        </div>
        <div class="stat high">
          <div class="stat-value">${high}</div>
          <div class="stat-label">High</div>
        </div>
        <div class="stat medium">
          <div class="stat-value">${medium}</div>
          <div class="stat-label">Medium</div>
        </div>
        <div class="stat low">
          <div class="stat-value">${low}</div>
          <div class="stat-label">Low/Info</div>
        </div>
      </div>
    </header>

    <main>`;

    for (const [tool, toolResults] of Object.entries(results)) {
      if (Array.isArray(toolResults) && toolResults.length > 0) {
        html += `
      <section>
        <h2>${tool.toUpperCase()} (${toolResults.length})</h2>`;

        toolResults.forEach(result => {
          html += `
        <div class="result">
          <div class="result-title">
            ${this.escapeHTML(result.title || 'Finding')}
            ${result.severity ? `<span class="severity ${result.severity}">${result.severity}</span>` : ''}
          </div>
          ${result.subtitle ? `<div class="result-subtitle">${this.escapeHTML(result.subtitle)}</div>` : ''}
          ${result.value ? `<div class="result-value">${this.escapeHTML(result.value)}</div>` : ''}
        </div>`;
        });

        html += `
      </section>`;
      }
    }

    html += `
    </main>

    <footer>
      <p>Report generated by <a href="https://www.tryharder.space" target="_blank">TryHarder Security Suite</a></p>
      <p>Created by <a href="https://github.com/a0x194" target="_blank">a0x194</a></p>
    </footer>
  </div>
</body>
</html>`;

    this.download(html, `${filename}.html`, 'text/html');
  },

  /**
   * Trigger download
   */
  download(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },

  /**
   * Escape CSV special characters
   */
  escapeCSV(str) {
    if (!str) return '';
    return str.replace(/"/g, '""');
  },

  /**
   * Escape HTML special characters
   */
  escapeHTML(str) {
    if (!str) return '';
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
};
